'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowLeft,ArrowRight,Volume2,Lightbulb,RotateCcw,Check,Mic,Square} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {lessons,glossary,wordCount,levelInfo,grammarGuide} from '@/lib/curriculum';
import type {Lesson,Profile,Activity} from '@/lib/curriculum';
import {request,say} from '@/lib/client';
export function Scene({object,position,surface}:{object:string;position:string;surface:string}){const y=position==='on'?50:position==='under'?150:98;return <svg className="scene" viewBox="0 0 240 210" role="img" aria-label={`${object} ${position} the ${position==='in'?'box':surface}`}><rect x="30" y="190" width="180" height="3" rx="2" fill="#cad5c5"/>{surface==='box'||position==='in'?<><rect x="68" y="61" width="104" height="103" rx="5" fill="#e8c78c" stroke="#916e38" strokeWidth="3"/><path d="M68 61l25-20h60l19 20" fill="#f6dcae" stroke="#916e38" strokeWidth="3"/></>:<><rect x="35" y="79" width="170" height="13" rx="5" fill="#ba895b"/><path d="M49 92v97m142-97v97" stroke="#8e633d" strokeWidth="10"/>{surface==='chair'&&<path d="M52 76V22h130v54" stroke="#ba895b" strokeWidth="9" fill="none"/>}</>}<text x="120" y={y+20} textAnchor="middle" fontSize="48">{glossary[object]?.picture||'⚽'}</text></svg>}
export default function LessonPlayer({lesson,profile,onExit,onSaved,startAt=0}:{startAt?:number;lesson:Lesson;profile:Profile;onExit:()=>void;onSaved:()=>Promise<void>}){
const [index,setIndex]=useState(startAt),[selected,setSelected]=useState(''),[written,setWritten]=useState(''),[tiles,setTiles]=useState<number[]>([]),[help,setHelp]=useState<string[]>([]),[first,setFirst]=useState<string|null>(null),[feedback,setFeedback]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[picked,setPicked]=useState(false),[audioPlayed,setAudioPlayed]=useState(false);const [attempt,setAttempt]=useState(()=>crypto.randomUUID());const a=lesson.activities[index];const guide=grammarGuide(a.sourceLessonId??lesson.id);
useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);
function assist(kind:string){setHelp(h=>h.includes(kind)?h:[...h,kind])}
function listen(){try{say(a.passage||a.audio||a.prompt,profile.rate);setAudioPlayed(true);if(a.kind==='build'||a.kind==='spell'||a.kind==='match'||(a.skill==='reading'&&!!a.passage))assist('model-audio')}catch(e){setError((e as Error).message)}}
function next(){if(index===lesson.activities.length-1){setDone(true);return}setIndex(index+1);setSelected('');setWritten('');setTiles([]);setHelp([]);setFirst(null);setFeedback('');setChecked(false);setError('');setPicked(false);setAudioPlayed(false);setAttempt(crypto.randomUUID());window.speechSynthesis?.cancel()}
const response=['write','gap'].includes(a.kind)?written.trim():a.kind==='build'?tiles.map(i=>a.choices[i]).join(' '):a.kind==='spell'?tiles.map(i=>a.choices[i]).join(''):selected;
async function check(){if(!response)return;setBusy(true);setError('');try{const assistance=[...help];if(first!==null&&!assistance.includes('retry'))assistance.push('retry');const r=await request({action:'evidence',id:attempt,lessonId:a.sourceLessonId??lesson.id,activityId:a.id,firstResponse:first??response,response,assistance});setFirst(first??response);setChecked(r.evidence.correct||r.evidence.status==='pending-review');setFeedback(r.evidence.status==='pending-review'?'Your writing is saved for teacher review. You can continue.':r.evidence.correct?(r.evidence.status==='independent'?'You found it on your own!':'You found it with a little help. Well done for trying.'):`Let’s look again. ${a.hint}`);if(!r.evidence.correct&&r.evidence.status!=='pending-review')assist('hint');await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
if(done)return <section className="finish-card"><span className="finish-icon">🌱</span><p className="eyebrow">A LITTLE MORE GROWTH</p><h1>You explored {lesson.title.toLowerCase()}</h1><p>{lesson.objective}</p><p>You can stop here. We’ll have another little adventure when you’re ready.</p><button className="primary" onClick={onExit}>Back to my learning <ArrowRight size={18}/></button></section>;
return <div className="player"><div className="player-top"><button className="text-link" onClick={onExit}><ArrowLeft size={18}/> Save & finish later</button><span>Activity {index+1} of {lesson.activities.length}</span></div><Progress value={index/lesson.activities.length*100} aria-label="Lesson progress"/><div className={"activity-card "+(a.passage||a.kind==='write'?'extended-activity':'')}><p className="eyebrow">{lesson.level} · {a.kind==='discover'?'DISCOVER TOGETHER':a.kind==='check'?'TRY IT ON YOUR OWN':a.kind==='listen'?'LISTEN & FIND':'YOUR TURN'}</p><h1>{a.prompt}</h1>{a.passage&&<article className="activity-passage" aria-label="Reading passage">{a.passage}</article>}{profile.uk&&<p lang="uk" className="uk-line">{a.uk}</p>}<div className="activity-tools"><button className="secondary" onClick={listen}><Volume2 size={19}/>{audioPlayed?'Replay':'Listen'}</button><button className="secondary" onClick={()=>assist('hint')}><Lightbulb size={18}/> Help</button>{guide&&<button className="secondary" onClick={()=>assist('grammar-guide')}>Learn the pattern</button>}{a.kind==='listen'&&<button className="text-link" onClick={()=>assist('transcript')}>Show words</button>}</div>
{guide&&help.includes('grammar-guide')&&<section className="grammar-guide" aria-label="Grammar guide"><h2>Learn the pattern</h2><p>{guide.explanation}</p><ol>{guide.examples.map(e=><li key={e}>{e}</li>)}</ol><p><b>Watch out:</b> {guide.pitfall}</p><small>Using the guide records this attempt as supported.</small></section>}{help.includes('transcript')&&<p className="transcript">{a.audio}</p>}{help.includes('hint')&&<div className="hint-box"><Lightbulb size={20}/><p>{a.hint} {a.scene&&'On is above the surface. Under is below it. In is inside.'}</p></div>}
{a.kind==='discover'&&<><Scene {...a.scene!}/><p className="discovery-caption">The cat is <strong>under</strong> the chair.</p></>}
{a.scene&&['build','check'].includes(a.kind)&&<Scene {...a.scene}/>}
{a.kind==='place'&&<><button className={'pick-ball '+(picked?'selected':'')} onClick={()=>setPicked(true)} aria-pressed={picked}>⚽ {picked?'Now choose a place':'Tap to pick up the ball'}</button><div className="choices">{a.choices.map(pos=><button disabled={!picked||checked} key={pos} className={'picture-choice '+(selected===pos?'selected':'')} aria-pressed={selected===pos} onClick={()=>setSelected(pos)}><Scene object="ball" position={pos} surface="table"/><span>{pos}</span></button>)}</div></>}
{['listen','match','check'].includes(a.kind)&&<div className={'choices '+(!a.pictures&&!a.scene?'long-choices':'')}>{a.choices.map(choice=><button key={choice} disabled={checked} aria-pressed={selected===choice} aria-label={a.pictures?`${choice} picture`:choice} className={'picture-choice '+(selected===choice?'selected':'')} onClick={()=>setSelected(choice)}>{a.scene&&a.kind==='listen'?<Scene {...a.scene} position={choice}/>:a.pictures?<span className="choice-emoji">{glossary[choice]?.picture}</span>:<span>{choice}</span>}{a.kind==='match'&&<span className="sr-only">{choice}</span>}</button>)}</div>}
{['build','spell'].includes(a.kind)&&<><div className="tile-answer" aria-label="Your answer">{tiles.length?tiles.map((n,i)=><button key={i} disabled={checked} onClick={()=>setTiles(tiles.filter((_,j)=>j!==i))}>{a.choices[n]}</button>):<p>{a.kind==='spell'?'Tap the letters in order':'Tap the words in order'}</p>}</div><div className="word-bank">{a.choices.map((word,i)=><button key={i} disabled={checked||tiles.includes(i)} onClick={()=>setTiles([...tiles,i])}>{word}</button>)}</div><button className="text-link" onClick={()=>setTiles([])} disabled={checked}><RotateCcw size={16}/> Start again</button></>}
{a.kind==='gap'&&<label className="field gap-response">Type the missing word or words<input disabled={checked} value={written} autoComplete="off" spellCheck={false} maxLength={120} onChange={e=>setWritten(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&response&&!busy&&!checked)void check()}}/></label>}{a.kind==='write'&&<section className="writing-task"><label htmlFor="written-response">Your response</label><p>{a.minWords}–{a.maxWords} words. A teacher reviews your ideas and language using these criteria.</p><ul>{a.rubric?.map(r=><li key={r}>{r}</li>)}</ul><textarea id="written-response" rows={9} maxLength={4000} disabled={checked} value={written} onChange={e=>setWritten(e.target.value)} aria-describedby="word-count"/><p id="word-count" className="small" aria-live="polite">{wordCount(written)} words · expected {a.minWords}–{a.maxWords}</p></section>}{feedback&&<div role="status" className={'feedback '+(checked?'correct':'')}>{checked&&<Check/>}{feedback}</div>}{error&&<p role="alert" className="error">{error}</p>}<div className="activity-footer"><p>{a.kind==='check'?'Help is always available.':'Take your time. You can try again.'}</p>{a.kind==='discover'||checked?<button className="primary" onClick={next}>Next <ArrowRight size={18}/></button>:<button className="primary" disabled={!response||busy||(a.kind==='write'&&(wordCount(response)<(a.minWords??1)||wordCount(response)>(a.maxWords??300)))} onClick={check}>{busy?'Saving…':a.kind==='write'?'Submit for teacher review':'Try my answer'} <Check size={18}/></button>}</div></div></div>}
export function Speaking({profile}:{profile:Profile}){const advanced=!['pre-A1','A1'].includes(levelInfo(profile.level).id);const speakingPrompts:Record<string,string>={A2:'Describe a school trip you enjoyed. Say where you went, what you did, and why you liked it.',B1:'Explain which school club you would start and give two reasons for your choice.',B2:'Compare two ways to reduce food waste at school. Recommend one and respond to a possible objection.',C1:'A school wants a wildlife garden but needs space for games. Reconcile the two viewpoints in a balanced proposal.',C2:'Reformulate the claim that a quiet classroom is always a better classroom. Preserve its useful insight while qualifying its assumptions.'};const speakingPrompt=speakingPrompts[profile.level]||'I can see a rabbit.';const [url,setUrl]=useState(''),[recording,setRecording]=useState(false),[error,setError]=useState('');const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current)},[]);useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);async function record(){try{setError('');stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream.current);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>chunks.push(e.data);r.onstop=()=>{setUrl(URL.createObjectURL(new Blob(chunks,{type:r.mimeType})));stream.current?.getTracks().forEach(t=>t.stop());setRecording(false)};r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop()},advanced?120000:20000)}catch{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setError('The microphone could not start. Check browser permission or say the sentence to an adult.')}}return <section className="white-card speaking"><h2>Say it your way</h2><p>{speakingPrompt} Listen, respond, and play it back with an adult.</p><div className="activity-tools"><button className="secondary" onClick={()=>{try{say(speakingPrompt,profile.rate)}catch(e){setError((e as Error).message)}}}><Volume2 size={18}/> Model audio</button>{profile.microphone?<button className="primary" onClick={()=>recording?recorder.current?.stop():record()}>{recording?<Square size={18}/>:<Mic size={18}/>} {recording?'Stop recording':advanced?'Record · up to 2 min':'Record · up to 20 sec'}</button>:<p>Ask an adult to enable the microphone in preferences.</p>}</div>{url&&<><audio controls src={url}/><button className="text-link" onClick={()=>setUrl('')}>Delete recording</button></>}<p className="small">Recording stays in this page and is removed when you leave. Listen together with an adult; no automatic speaking or pronunciation score.</p>{error&&<p className="error" role="alert">{error}</p>}</section>}
