import {localFetch as fetch} from '@/lib/local-store';
'use client';
import {useEffect,useRef,useState} from 'react';
import {Sparkles,ArrowRight,RotateCcw} from 'lucide-react';
import {lessons,normalizeLevel} from '@/lib/curriculum';
import type {Lesson,Profile} from '@/lib/curriculum';
import {domains} from '@/lib/vocabulary';
import type {Domain} from '@/lib/vocabulary';
import LessonPlayer from './lesson-player';
import Vocabulary from './vocabulary';
type Plan={title:string;rationale?:string;source:string;notice:string;level:Lesson['level'];domain:Domain;exercises:{id:string;lessonId:string;reason:string;observed:string}[];words:{id:string;word:string;reason:string;observed:string}[]};
export default function SmartPractice({profile,onSaved}:{profile:Profile;onSaved:()=>Promise<void>}){
 const [domain,setDomain]=useState<Domain>('general'),[plan,setPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[stage,setStage]=useState<'plan'|'lesson'|'words'>('plan');const controller=useRef<AbortController|null>(null);
 async function build(mode:'model'|'rules'){setBusy(true);setError('');controller.current=new AbortController();try{const r=await fetch('/api/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain,mode}),signal:controller.current.signal});const result=await r.json() as Plan&{error?:string};if(!r.ok)throw new Error(result.error);setPlan(result);setStage('plan')}catch(e){setError((e as Error).name==='AbortError'?'Stopped preparing. You can use instant practice below.':(e as Error).message)}finally{setBusy(false)}}
 if(stage==='lesson'&&plan){const session:Lesson={id:'smart-'+plan.level,level:plan.level,title:plan.title,topic:'school',objective:'Revisit the skills selected from your recent learning evidence.',words:[],activities:plan.exercises.map(x=>{const l=lessons.find(l=>l.id===x.lessonId)!;return {...l.activities.find(a=>a.id===x.id)!,sourceLessonId:l.id}})};return <LessonPlayer lesson={session} profile={profile} onSaved={onSaved} onExit={()=>setStage('words')}/>}
 if(stage==='words'&&plan)return <><button className="text-link" onClick={()=>setStage('plan')}>Back to my practice plan</button><Vocabulary key={plan.domain+plan.title} profile={profile} initialDomain={plan.domain} focusIds={plan.words.map(w=>w.id)}/></>;
 return <><div className="page-heading"><div><p className="eyebrow">YOUR HISTORY, YOUR NEXT STEP</p><h1>Smart practice</h1><p>A short lesson selected from your recent answers and recall.</p></div><Sparkles size={36}/></div><section className="smart-builder white-card"><div><h2>Build my next lesson</h2><p>Your {normalizeLevel(profile.level)} exercise results, support used, and vocabulary recall dates guide this session. Practice is prepared on this device.</p><label className="field">Vocabulary focus<select value={domain} disabled={busy} onChange={e=>setDomain(e.target.value as Domain)}>{domains.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label><div className="activity-tools"><button className="primary" disabled={busy} onClick={()=>void build('rules')}>Build my practice</button>{busy&&<button className="text-link" onClick={()=>controller.current?.abort()}>Cancel</button>}</div>{busy&&<p role="status">Preparing your practice.</p>}{error&&<p role="alert" className="error">{error}</p>}</div><aside><b>What shapes your lesson?</b><ol><li>Try recent mistakes on another attempt.</li><li>Gradually reduce support.</li><li>Recall skills and words after a delay.</li><li>Add a little new material when you are ready.</li></ol><p className="small">Practice uses checked questions and answer keys. Your teacher can also write and review new stories.</p></aside></section>{plan&&<section className="practice-plan" aria-live="polite"><div className="section-heading"><div><span className="tag">History-based lesson</span><h2>{plan.title}</h2><p>{plan.notice}</p>{plan.rationale&&<p>{plan.rationale}</p>}</div></div><div className="plan-grid">{plan.exercises.map((x,i)=>{const l=lessons.find(l=>l.id===x.lessonId)!;const a=l.activities.find(a=>a.id===x.id)!;return <article className="white-card" key={x.id}><span className="eyebrow">STEP {i+1} · {a.skill}</span><h3>{l.grammarFocus||l.title}</h3><p>{x.reason}</p></article>})}</div>{plan.words.length>0&&<section className="white-card selected-words"><h3>Words to revisit or discover</h3>{plan.words.map(w=><p key={w.id}><b>{w.word}</b> — {w.reason}</p>)}</section>}<div className="activity-tools"><button className="primary" onClick={()=>setStage('lesson')}>Start my lesson <ArrowRight size={18}/></button><button className="secondary" onClick={()=>setStage('words')}>Practise the words</button><button className="text-link" disabled={busy} onClick={()=>void build('rules')}><RotateCcw size={16}/> Use instant practice</button></div></section>}</>;
}
