'use client';
import {useState,useEffect} from 'react';
import {Volume2,ArrowLeft,ArrowRight} from 'lucide-react';
import {stories,glossary,lessonsForLevel,normalizeLevel} from '@/lib/curriculum';
import type {Profile,Lesson} from '@/lib/curriculum';
import type {Draft} from '@/lib/client';
import {request,say} from '@/lib/client';
export default function StoryLibrary({profile,drafts,onSaved,onStart}:{onStart:(lesson:Lesson)=>void;profile:Profile;drafts:Draft[];onSaved:()=>Promise<void>}){const [selected,setSelected]=useState<string|null>(null),[highlight,setHighlight]=useState(-1),[meaning,setMeaning]=useState(''),[response,setResponse]=useState(''),[first,setFirst]=useState<string|null>(null),[support,setSupport]=useState<string[]>([]),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState('');const story=stories.find(s=>s.id===selected),draft=drafts.find(d=>d.id===selected),text=story?.lines.join(' ')||draft?.text||'';useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);function open(id:string){setSelected(id);setHighlight(-1);setMeaning('');setResponse('');setFirst(null);setSupport([]);setFeedback('');setError('');setAttempt(crypto.randomUUID())}function listen(){try{setSupport(s=>[...new Set([...s,'story-audio'])]);say(text,profile.rate,setHighlight,()=>setHighlight(-1))}catch(e){setError((e as Error).message)}}
if(!selected)return <><div className="page-heading"><div><p className="eyebrow">OPEN A LITTLE WORLD</p><h1>Story time</h1><p>Read it, hear it, and discover words along the way.</p></div></div><div className="library-grid">{(['pre-A1','A1'].includes(normalizeLevel(profile.level))?stories:[]).map((s,i)=><button className={'story-card '+['green','pink','blue'][i]} key={s.id} onClick={()=>open(s.id)}><span className="cover-emoji">{s.emoji}</span><span className="eyebrow">5 SHORT SENTENCES</span><h2>{s.title}</h2><p>Read & listen <ArrowRight size={16}/></p></button>)}{lessonsForLevel(profile.level).filter(l=>l.level!=='A1'&&!l.grammarFocus).map(l=><button className="story-card blue" key={l.id} onClick={()=>onStart(l)}><span className="cover-emoji">📖</span><span className="eyebrow">{l.level} · READ & THINK</span><h2>{l.title}</h2><p>Read & practise <ArrowRight size={16}/></p></button>)}{drafts.filter(d=>d.status==='published'&&(normalizeLevel(d.level||'A1')==='pre-A1'?'A1':normalizeLevel(d.level||'A1'))===(['pre-A1','A1'].includes(normalizeLevel(profile.level))?'A1':normalizeLevel(profile.level))).map(d=><button className="story-card blue" key={d.id} onClick={()=>open(d.id)}><span className="cover-emoji">📖</span><span className="eyebrow">FROM YOUR TEACHER</span><h2>{d.title}</h2><p>Read & listen <ArrowRight size={16}/></p></button>)}</div></>;
let offset=0;return <><button className="text-link" onClick={()=>{setSelected(null);window.speechSynthesis?.cancel()}}><ArrowLeft size={18}/> All stories</button><section className="reading-card"><span className="cover-emoji">{story?.emoji||'📖'}</span><h1>{story?.title||draft?.title}</h1><button className="secondary" onClick={listen}><Volume2 size={18}/> Listen to the story</button><p className="reading-text">{text.split(/(\s+)/).map((word,i)=>{const start=offset;offset+=word.length;const clean=word.toLowerCase().replace(/[^a-z]/g,'');return glossary[clean]?<button key={i} className={highlight>=start&&highlight<offset?'spoken':''} onClick={()=>{setMeaning(`${word}: ${glossary[clean].picture} ${glossary[clean].uk}`);setSupport(s=>[...new Set([...s,'glossary'])])}}>{word}</button>:<span key={i} className={highlight>=start&&highlight<offset?'spoken':''}>{word}</span>})}</p><p className="small">Tap a word for its picture and Ukrainian meaning. Highlighting follows audio when your browser supports it.</p>{meaning&&<p className="hint-box" role="status">{meaning}</p>}{story&&<div className="story-check"><h2>{story.question}</h2><div className="choices text-choices">{story.choices.map(c=><button key={c} aria-pressed={response===c} className={'secondary '+(response===c?'selected':'')} onClick={()=>setResponse(c)}>{c}</button>)}</div><button className="primary" disabled={!response||busy||feedback.startsWith('You found')} onClick={async()=>{setBusy(true);setError('');try{const r=await request({action:'evidence',id:attempt,lessonId:'stories',activityId:story.id,firstResponse:first??response,response,assistance:first?[...support,'retry']:support});setFirst(first??response);setFeedback(r.evidence.correct?'You found the answer!':'Read the story once more and try again.');await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Check my answer</button><p role="status">{feedback}</p></div>}{error&&<p className="error" role="alert">{error}</p>}</section></>}
