import {localFetch as fetch} from '@/lib/local-store';
'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,BookOpen,Lightbulb,Volume2,RotateCcw} from 'lucide-react';
import {domains,frequencyLabel,normaliseWord,vocabulary,vocabularySource} from '@/lib/vocabulary';
import type {Domain,Term,WordRecord} from '@/lib/vocabulary';
import type {Profile} from '@/lib/curriculum';
import {normalizeLevel} from '@/lib/curriculum';
import {say} from '@/lib/client';
type Item={term:Term;record:WordRecord|null;reason:string};
type State={items:Item[];records:WordRecord[];introduced:number;newRemaining:number;dueCount:number};
export default function Vocabulary({profile,initialDomain='general',focusIds=[]}:{profile:Profile;initialDomain?:Domain;focusIds?:string[]}){
 const [domain,setDomain]=useState<Domain>(initialDomain),[state,setState]=useState<State|null>(null),[items,setItems]=useState<Item[]>([]),[index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[help,setHelp]=useState(false),[result,setResult]=useState<WordRecord|null>(null),[attempt,setAttempt]=useState(()=>crypto.randomUUID()),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 async function load(d:Domain){setBusy(true);setError('');try{const r=await fetch('/api/vocabulary?domain='+d,{cache:'no-store'});const s=await r.json() as State&{error?:string};if(!r.ok)throw new Error(s.error);setState(s);setItems([...s.items].sort((a,b)=>Number(focusIds.includes(b.term.id))-Number(focusIds.includes(a.term.id))));setIndex(0);setAnswer('');setHelp(false);setResult(null);setAttempt(crypto.randomUUID())}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void load(domain)},[domain,profile.level]);
 const item=items[index];
 async function check(){if(!item)return;setBusy(true);setError('');try{const r=await fetch('/api/vocabulary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain,termId:item.term.id,answer,assisted:help,attemptId:attempt})});const data:any=await r.json();if(!r.ok)throw new Error(data.error);setResult(data.record);setState(s=>s?{...s,records:[...s.records.filter(x=>x.termId!==item.term.id),data.record]}:s)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function next(){setIndex(i=>i+1);setAnswer('');setHelp(false);setResult(null);setAttempt(crypto.randomUUID())}
 const visible=vocabulary.filter(t=>(domain==='general'?t.domain==='general':t.domain===domain)&&(t.word.includes(search.toLowerCase())||t.definition.toLowerCase().includes(search.toLowerCase())));
 return <><div className="page-heading"><div><p className="eyebrow">USEFUL WORDS, SMALL SETS</p><h1>Your word garden</h1><p>Recall common words first. Add terminology for a topic you care about.</p></div><BookOpen size={34}/></div><div className="filter-row" aria-label="Vocabulary domain">{domains.map(d=><button key={d.id} disabled={busy} className={'filter '+(domain===d.id?'active':'')} aria-pressed={domain===d.id} onClick={()=>setDomain(d.id)}>{d.label}</button>)}</div><p>{domains.find(d=>d.id===domain)?.description} Your practice follows {normalizeLevel(profile.level)}.</p>
 <div className="vocab-layout"><section className="white-card recall-card"><p className="eyebrow">{item?`WORD ${index+1} OF ${items.length}`:'A LITTLE PRACTICE'}</p>{error&&<p role="alert" className="error">{error}</p>}{busy&&!state?<p role="status">Preparing your words…</p>:item?<><span className="tag">{item.reason}</span><h2>{item.term.definition}</h2><p className="recall-sentence">{item.term.sentence.replace(new RegExp('\\b'+item.term.word+'\\b','gi'),'________')}</p><p className="small">Recall the dictionary word: {item.term.word.length} letters, beginning with “{item.term.word[0]}”.</p><label className="field">Which word completes the sentence?<input autoComplete="off" spellCheck={false} disabled={!!result||busy} value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!result&&answer.trim())void check()}}/></label><div className="activity-tools"><button className="secondary" disabled={!!result} onClick={()=>setHelp(true)}><Lightbulb size={17}/> Reveal word</button>{help&&<><b>{item.term.word}</b><button className="icon-button" aria-label="Listen to this word" onClick={()=>{try{say(item.term.word,profile.rate)}catch(e){setError((e as Error).message)}}}><Volume2 size={18}/></button>{profile.uk&&<span lang="uk">{item.term.uk}</span>}</>}</div>{result?<div className="feedback correct" role="status"><div><b>{normaliseWord(answer)===normaliseWord(item.term.word)?result.status==='independent'?'Remembered independently.':'Remembered with support.':`The word is “${item.term.word}”.`}</b><p>{item.term.sentence}</p><p>Next recall: {new Date(result.due).toLocaleDateString()}. {result.status!=='independent'?'We will revisit this sooner.':''}</p><button className="primary" onClick={next}>Next word <ArrowRight size={17}/></button></div></div>:<button className="primary" disabled={!answer.trim()||busy} onClick={()=>void check()}>{busy?'Saving…':'Check recall'}</button>}</>:<><h2>{items.length?'Your small set is complete':'Room for your words to settle'}</h2><p>Review words return when they are due. You can still explore meanings in the dictionary below.</p><button className="secondary" onClick={()=>void load(domain)} disabled={busy}><RotateCcw size={17}/> Check next set</button></>}</section><aside className="white-card word-plan"><h2>A manageable rhythm</h2><p><b>Up to 5 words per set.</b> Due reviews come first, with at most 5 new words per day across all topics.</p><p>A specialist topic introduces at most 2 new domain words per day. Everyday English uses common vocabulary.</p><p>Independent recall grows the interval: 1, 3, 7, 14, then 30 days. A mistake or reveal brings the word back after 1 day.</p><p className="small">Day boundaries use UTC. A practice result describes this attempt; it is not proof of permanent mastery.</p>{state&&<div className="word-stats"><span><b>{state.records.length}</b> words practised</span><span><b>{state.dueCount}</b> due in this topic</span></div>}</aside></div>
 <details className="dictionary" onToggle={e=>{if(e.currentTarget.open&&item&&!result)setHelp(true)}}><summary>Explore the dictionary · opening it counts as support for the current word</summary><div className="section-heading"><div><h2>A dictionary with priorities</h2><p>Explore freely; browsing a definition does not introduce it into your recall schedule.</p></div></div><label className="field dictionary-search">Find a word or meaning<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search this topic"/></label><div className="dictionary-grid">{visible.sort((a,b)=>(b.zipf??-1)-(a.zipf??-1)).map(t=><article className="white-card dictionary-entry" key={t.id}><div><h3>{t.word}</h3><button className="icon-button" aria-label={`Listen to ${t.word}`} onClick={()=>{try{say(t.word,profile.rate)}catch(e){setError((e as Error).message)}}}><Volume2 size={17}/></button></div><span className="frequency-label">{frequencyLabel(t.zipf)}{t.zipf!==null?` · ${t.zipf.toFixed(2)}`:''}</span><p>{t.definition}</p><p className="small">{t.sentence}</p>{profile.uk&&<p lang="uk">{t.uk}</p>}<span className="small">{t.level} practice {t.domain!=='general'?`· Useful for ${t.domain}`:''}</span></article>)}</div>{!visible.length&&<p>No matching words in this topic.</p>}<details className="frequency-notes"><summary>How frequency helps us choose words</summary><p>General-English estimates come from <a href={vocabularySource.url} target="_blank" rel="noreferrer">wordfreq {vocabularySource.version}</a>, using several corpora with data through approximately 2021. The Zipf scale is logarithmic: 5 is roughly 100 occurrences per million words, and 3 is roughly one. Common here means a score of 4 or more; very common means 5 or more.</p><p>Frequency is not a CEFR level and does not measure a word's value in your chosen field. Scores combine meanings of the same spelling. Our level labels describe these teaching examples, not certified word levels. Unlisted estimates remain unknown.</p><p>Frequency data: Robyn Speer and contributors, CC BY-SA 4.0. <a href="./wordfreq-NOTICE.txt" target="_blank" rel="noreferrer">Full source attribution and license notices</a>. Definitions and examples were written for this learning bank.</p></details></details></>;
}
