import {localFetch as fetch} from '@/lib/local-store';
'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Search,Volume2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {domains,vocabulary} from '@/lib/vocabulary';
import type {Domain} from '@/lib/vocabulary';
import type {WordKnowledge,WordState} from '@/lib/word-knowledge';
import {say} from '@/lib/client';
type Atlas={count:number;bands:number[];entries:[string,number][];source:{url:string;version:string;license:string;notice:string}};
type UkrainianGloss={uk:string;alternatives?:string[];noteUk?:string;example?:string;exampleUk?:string;source:'authored'|'dictionary'|'machine';certainty:'reviewed'|'lexical'|'unverified'};
type Entry={word:string;zipf:number;rank:number};
type Progress={knowledge:WordKnowledge[];paths:{level:string;passed:number;total:number}[]};
const states:{id:WordState|'untested';label:string}[]=[{id:'retained',label:'Retained after a delay'},{id:'recalled',label:'Recalled independently'},{id:'recognised',label:'Recognised'},{id:'with-support',label:'With support'},{id:'needs-review',label:'Needs review'},{id:'untested',label:'Not tested here'}];
const bands=[{min:1,max:100,label:'1–100'},{min:101,max:1000,label:'101–1,000'},{min:1001,max:5000,label:'1,001–5,000'},{min:5001,max:10000,label:'5,001–10,000'},{min:10001,max:20000,label:'10,001–20,000'},{min:20001,max:50000,label:'20,001–50,000'},{min:50001,max:100000,label:'50,001–100,000'},{min:1,max:100000,label:'All 100,000'}];
export default function VocabularyAtlas({onPractise,rate}:{onPractise:(domain:Domain)=>void;rate:number}){
 const [atlas,setAtlas]=useState<Atlas|null>(null),[ukrainian,setUkrainian]=useState<Record<string,UkrainianGloss>>({}),[progress,setProgress]=useState<Progress|null>(null),[error,setError]=useState(''),[progressError,setProgressError]=useState(''),[query,setQuery]=useState(''),[band,setBand]=useState(0),[domain,setDomain]=useState<Domain|'all'>('all'),[state,setState]=useState<WordState|'untested'|'all'>('all'),[page,setPage]=useState(0),[selected,setSelected]=useState<Entry|null>(null);
 async function loadProgress(signal?:AbortSignal){try{const r=await fetch('/api/lexicon/progress',{cache:'no-store',signal});const p:any=await r.json();if(!r.ok)throw new Error(p.error);setProgress(p);setProgressError('')}catch(e){if((e as Error).name!=='AbortError')setProgressError((e as Error).message)}}
 useEffect(()=>{const c=new AbortController();fetch('/lexicon/atlas.json',{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error('The word atlas could not be loaded.');return r.json() as Promise<Atlas>}).then(setAtlas).catch(e=>{if(e.name!=='AbortError')setError(e.message)});fetch('/lexicon/uk-translations.json',{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error('The Ukrainian word list is not available yet.');return r.json() as Promise<{translations:Record<string,UkrainianGloss>}>}).then(x=>setUkrainian(x.translations)).catch(e=>{if(e.name!=='AbortError')setError(e.message)});void loadProgress(c.signal);return()=>c.abort()},[]);
 useEffect(()=>{setPage(0)},[query,band,domain,state]);
 const knowledge=useMemo(()=>new Map(progress?.knowledge.map(k=>[k.word,k])??[]),[progress]);
 const entries=useMemo(()=>atlas?.entries.map(([word,zipf],i)=>({word,zipf,rank:i+1}))??[],[atlas]);
 const termMap=useMemo(()=>{const m=new Map<string,typeof vocabulary>();for(const t of vocabulary){const list=m.get(t.word)??[];list.push(t);m.set(t.word,list)}return m},[]);
 const filtered=useMemo(()=>{const range=bands[band];const q=query.trim().toLowerCase();return entries.filter(e=>e.rank>=range.min&&e.rank<=range.max&&(!q||e.word.includes(q)||ukrainian[e.word]?.uk.toLowerCase().includes(q))&&(domain==='all'||termMap.get(e.word)?.some(t=>t.domain===domain))&&(state==='all'||(knowledge.get(e.word)?.status??'untested')===state))},[entries,query,band,domain,state,knowledge,termMap,ukrainian]);
 const totals=useMemo(()=>{const counts:Record<string,number>={};for(const e of entries){const status=knowledge.get(e.word)?.status??'untested';counts[status]=(counts[status]??0)+1}return counts},[entries,knowledge]);
 const coverage=useMemo(()=>[100,1000,5000,10000,100000].map(limit=>({limit,demonstrated:entries.slice(0,limit).filter(e=>['recalled','retained'].includes(knowledge.get(e.word)?.status??'')).length})),[entries,knowledge]);
 const lastPage=Math.max(0,Math.ceil(filtered.length/50)-1),currentPage=Math.min(page,lastPage);const visible=filtered.slice(currentPage*50,currentPage*50+50);const meanings=selected?termMap.get(selected.word)??[]:[];
 return <><div className="page-heading"><div><p className="eyebrow">A BIG MAP. SMALL STEPS.</p><h1>Vocabulary atlas</h1><p>100,000 frequency-ranked word forms, with Ukrainian meanings where available. Translation coverage is still growing.</p></div><BookOpen size={34}/></div>{error&&<p className="error" role="alert">{error}</p>}{(!atlas||!Object.keys(ukrainian).length)&&!error&&<p role="status">Loading the frequency atlas and Ukrainian translations…</p>}
 <section className="atlas-knowledge white-card"><div className="section-heading"><div><h2>Your demonstrated vocabulary</h2><p>Evidence from your answers, spelling, and scheduled recall.</p></div><button className="text-link" onClick={()=>void loadProgress()}>Refresh evidence</button></div>{progressError?<p className="error" role="alert">{progressError}</p>:<><div className="atlas-stats"><div><strong>{progress?((totals.recalled??0)+(totals.retained??0)).toLocaleString():'—'}</strong><span>words recalled independently</span></div><div><strong>{progress?(totals.retained??0).toLocaleString():'—'}</strong><span>of those, retained after a delay</span></div><div><strong>{progress?(totals.recognised??0).toLocaleString():'—'}</strong><span>recognised; recall not yet shown</span></div><div><strong>{progress?(totals.untested??0).toLocaleString():'—'}</strong><span>not tested here</span></div></div><p className="small">This is a measured lower bound on your vocabulary, not a claim about every word you know. Delayed retention needs independent recall on dates at least seven days apart. A later error or support lowers the current evidence state.</p><div className="coverage-bands">{coverage.map(c=><div key={c.limit}><b>Top {c.limit.toLocaleString()}</b><span>{c.demonstrated.toLocaleString()} recalled / {c.limit.toLocaleString()}</span><progress max={c.limit} value={c.demonstrated} aria-label={`Recalled words among the top ${c.limit}`}/></div>)}</div></>}
 <details className="path-evidence"><summary>How passed exercises and levels contribute</summary><p>We count a word only when an activity directly tests it. Reading a passage or completing a C2 lesson does not mark all its words as known. A lesson below counts only when every scored activity has a latest independent success, including teacher-reviewed writing.</p><div className="path-counts">{progress?.paths.map(p=><span key={p.level}><b>{p.level}</b> {p.passed}/{p.total} sample lessons</span>)}</div><p className="small">These are practice records, not CEFR qualifications. The evidence covers the tested meanings, not every sense of a word.</p><p>Ukrainian dictionary mappings adapted from <a href="https://github.com/dmklinger/ukrainian" target="_blank" rel="noreferrer">dmklinger/ukrainian</a>, CC BY-SA 3.0. <a href="./lexicon/UKRAINIAN-SOURCES.txt" target="_blank" rel="noreferrer">Attribution and adaptation details</a>.</p></details></section>
 <section className="atlas-browse"><div className="section-heading"><div><h2>Explore by frequency and field</h2><p>Frequent words provide broad coverage. Specialist words matter when you need that field.</p></div></div><div className="filter-row atlas-bands" aria-label="Frequency bands">{bands.map((b,i)=><button className={'filter '+(band===i?'active':'')} aria-pressed={band===i} key={b.label} onClick={()=>setBand(i)}>{b.label}</button>)}</div><div className="atlas-filters"><label className="field"><span><Search size={16}/> Search this view</span><input type="search" placeholder="Find a word or Ukrainian meaning" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="field">Field<select aria-label="Atlas field" value={domain} onChange={e=>{setDomain(e.target.value as Domain|'all');setBand(7)}}><option value="all">All fields and general language</option>{domains.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label><label className="field">Learning evidence<select aria-label="Learning evidence" value={state} onChange={e=>setState(e.target.value as typeof state)}><option value="all">All evidence states</option>{states.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label></div>
 {domain!=='all'&&<div className="domain-intro"><div><b>{domains.find(d=>d.id===domain)?.label}</b><p>{domains.find(d=>d.id===domain)?.description} The curated terms are grouped as foundation, working vocabulary, or advanced. They form a starting syllabus for the field.</p></div><button className="primary" onClick={()=>onPractise(domain)}>Practise this field <ArrowRight size={17}/></button></div>}
 <div className="atlas-result-count" role="status">{atlas?`${filtered.length.toLocaleString()} words · ordered by frequency rank`:'Preparing words…'} <span>Page {currentPage+1} of {lastPage+1}</span></div><div className="atlas-table-wrap"><table className="atlas-table"><thead><tr><th>Rank</th><th>Word</th><th className="atlas-frequency">Frequency</th><th>Evidence</th><th className="atlas-field-column">Field</th></tr></thead><tbody>{visible.map(e=>{const k=knowledge.get(e.word);const terms=termMap.get(e.word)??[];return <tr key={e.word}><td>#{e.rank.toLocaleString()}</td><td><button className="atlas-word" onClick={()=>setSelected(e)}>{e.word}</button><span className="atlas-translation" lang="uk">{terms.find(t=>t.domain===domain)?.uk??terms[0]?.uk??ukrainian[e.word]?.uk??"No Ukrainian gloss"}</span><span className="atlas-translation-source">{terms.length?"Course glossary":ukrainian[e.word]?.source==="authored"?"Reviewed Ukrainian":ukrainian[e.word]?.source==="dictionary"?"Bilingual dictionary":"Translation not yet available"}</span></td><td className="atlas-frequency">{e.zipf.toFixed(2)} <span>Zipf</span></td><td><span className={'word-state '+(k?.status??'untested')}>{states.find(s=>s.id===(k?.status??'untested'))?.label}</span></td><td className="atlas-field-column">{terms.map(t=><span className="atlas-field" key={t.id}>{domains.find(d=>d.id===t.domain)?.label}{t.importance?' · '+t.importance:''}</span>)}</td></tr>})}</tbody></table></div>{atlas&&!visible.length&&<p className="notice">No words match these filters. Try All 100,000 or a different field.</p>}<div className="atlas-pagination"><button className="secondary" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}><ArrowLeft size={16}/> Previous</button><span>{filtered.length?currentPage*50+1:0}–{Math.min((currentPage+1)*50,filtered.length)} of {filtered.length.toLocaleString()}</span><button className="secondary" disabled={currentPage===lastPage} onClick={()=>setPage(currentPage+1)}>Next <ArrowRight size={16}/></button></div></section>
 <details className="frequency-notes"><summary>Source, ranking, and coverage</summary><p>The atlas contains 100,000 selected single-word forms from <a href="https://github.com/rspeer/wordfreq" target="_blank" rel="noreferrer">wordfreq 3.1.1</a>, sorted by estimated English frequency. Equal-frequency items keep their source order. Ranks refer to this filtered list; inflections, names, abbreviations, borrowed words, and corpus artifacts may appear. They are not 100,000 distinct dictionary lemmas.</p><p>Zipf 5 is approximately 100 occurrences per million words; Zipf 3 is approximately one. Estimates combine senses and corpora through approximately 2021. Frequency does not determine CEFR level or professional proficiency. The atlas supplies frequency data; original definitions and examples cover the curated learning bank. Other entries link to an external dictionary.</p><p>Ukrainian meanings are available for about 17,000 atlas entries. Common function words include authored usage explanations. Missing meanings are marked explicitly; dictionary translations can vary with context.</p><p>Derived frequency data: CC BY-SA 4.0, Robyn Speer and contributors. <a href="./wordfreq-NOTICE.txt" target="_blank" rel="noreferrer">Full attribution and corpus notices</a> · <a href="./lexicon/atlas.json" download>Download the attributed English frequency list</a> · <a href="./lexicon/uk-translations.json" download>Download available Ukrainian meanings</a></p></details>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="atlas-word-dialog"><DialogHeader><DialogTitle>{selected?.word}</DialogTitle><DialogDescription>Rank #{selected?.rank.toLocaleString()} · General-English Zipf {selected?.zipf.toFixed(2)}</DialogDescription></DialogHeader>{selected&&<><button className="secondary" onClick={()=>{try{say(selected.word,rate)}catch(e){setError((e as Error).message)}}}><Volume2 size={17}/> Hear this word</button>{selected&&ukrainian[selected.word]&&<article className="atlas-meaning uk-gloss"><span className="tag">{ukrainian[selected.word].source==="authored"?"Reviewed Ukrainian":ukrainian[selected.word].source==="dictionary"?"Bilingual dictionary":"Machine translation"}</span><p lang="uk"><b>{ukrainian[selected.word].uk}</b></p>{ukrainian[selected.word].alternatives?.length?<p lang="uk">Other translations: {ukrainian[selected.word].alternatives?.join(", ")??""}</p>:null}{ukrainian[selected.word].noteUk&&<p lang="uk">{ukrainian[selected.word].noteUk}</p>}{ukrainian[selected.word].example&&<p>{ukrainian[selected.word].example}<br/><span lang="uk">{ukrainian[selected.word].exampleUk}</span></p>}</article>}{meanings.map(t=><article className="atlas-meaning" key={t.id}><span className="tag">{domains.find(d=>d.id===t.domain)?.label} · {t.importance??'foundation'}</span><p><b>{t.definition}</b></p><p>{t.sentence}</p><p lang="uk">{t.uk}</p><button className="text-link" onClick={()=>onPractise(t.domain)}>Open this practice field <ArrowRight size={16}/></button></article>)}{!meanings.length&&!ukrainian[selected.word]&&<p>This word is in the frequency list but its Ukrainian translation is not yet included.</p>}<a className="text-link" href={'https://en.wiktionary.org/wiki/'+encodeURIComponent(selected.word)} target="_blank" rel="noreferrer">Look up meanings in Wiktionary ↗</a><p className="small">{knowledge.get(selected.word)?.explanation??'No direct answer evidence for this word yet.'}</p></>}</DialogContent></Dialog></>;
}
