import advancedContent from './level-content.json' with {type:'json'};
import grammarContent from './grammar-content.json' with {type:'json'};
import grammarGuides from './grammar-guides.json' with {type:'json'};
export const grammarGuide=(lessonId:string)=>grammarGuides.find(g=>g.lessonId===lessonId);
export type Skill='listening'|'reading'|'sentences'|'spelling'|'speaking'|'writing';
export type Activity={id:string;sourceLessonId?:string;kind:'discover'|'listen'|'match'|'place'|'build'|'spell'|'check'|'write'|'gap';skill:Skill;item:string;prompt:string;uk:string;audio:string;answer:string;answers?:string[];choices:string[];hint:string;scene?:{object:string;position:string;surface:string};pictures?:boolean;passage?:string;minWords?:number;maxWords?:number;rubric?:string[];objective:string;reviewStatus:'approved';likelyErrors:string[]};
export type Level='pre-A1'|'A1'|'A2'|'B1'|'B2'|'C1'|'C2';
export type Lesson={level:Level;grammarFocus?:string;passage?:string;id:string;topic:string;title:string;objective:string;words:string[];activities:Activity[]};
export const topics=[{id:'animals',title:'Animal friends',desc:'Meet some new friends',emoji:'🐾',color:'green'},{id:'food',title:'Food & picnic',desc:'A tasty little adventure',emoji:'🍎',color:'pink'},{id:'school',title:'My school',desc:'Everyday discoveries',emoji:'🎒',color:'blue'}];
export const glossary:Record<string,{picture:string;uk:string}>={cat:{picture:'🐈',uk:'кіт'},dog:{picture:'🐕',uk:'собака'},rabbit:{picture:'🐇',uk:'кролик'},bird:{picture:'🐦',uk:'птах'},fish:{picture:'🐟',uk:'риба'},duck:{picture:'🦆',uk:'качка'},horse:{picture:'🐎',uk:'кінь'},cow:{picture:'🐄',uk:'корова'},sheep:{picture:'🐑',uk:'вівця'},frog:{picture:'🐸',uk:'жаба'},lion:{picture:'🦁',uk:'лев'},elephant:{picture:'🐘',uk:'слон'},apple:{picture:'🍎',uk:'яблуко'},banana:{picture:'🍌',uk:'банан'},orange:{picture:'🍊',uk:'апельсин'},bread:{picture:'🍞',uk:'хліб'},cheese:{picture:'🧀',uk:'сир'},egg:{picture:'🥚',uk:'яйце'},milk:{picture:'🥛',uk:'молоко'},water:{picture:'💧',uk:'вода'},juice:{picture:'🧃',uk:'сік'},carrot:{picture:'🥕',uk:'морква'},tomato:{picture:'🍅',uk:'помідор'},potato:{picture:'🥔',uk:'картопля'},cake:{picture:'🍰',uk:'торт'},rice:{picture:'🍚',uk:'рис'},sandwich:{picture:'🥪',uk:'бутерброд'},book:{picture:'📕',uk:'книга'},pencil:{picture:'✏️',uk:'олівець'},bag:{picture:'🎒',uk:'рюкзак'},ruler:{picture:'📏',uk:'лінійка'},pen:{picture:'🖊️',uk:'ручка'},crayon:{picture:'🖍️',uk:'кольоровий олівець'},chair:{picture:'🪑',uk:'стілець'},table:{picture:'▱',uk:'стіл'},door:{picture:'🚪',uk:'двері'},clock:{picture:'🕒',uk:'годинник'},window:{picture:'🪟',uk:'вікно'},computer:{picture:'💻',uk:'комп’ютер'},ball:{picture:'⚽',uk:'м’яч'},map:{picture:'🗺️',uk:'мапа'},notebook:{picture:'📓',uk:'зошит'},box:{picture:'📦',uk:'коробка'},in:{picture:'↘',uk:'у, всередині'},on:{picture:'↧',uk:'на'},under:{picture:'↓',uk:'під'}};
function activity(id:string,kind:Activity['kind'],skill:Skill,item:string,prompt:string,audio:string,answer:string,choices:string[],hint:string,extra:Partial<Activity>={}):Activity{return {id,kind,skill,item,prompt,audio,answer,choices,hint,uk:kind==='build'?'Склади речення зі слів.':kind==='spell'?'Склади слово з літер.':kind==='listen'?'Послухай та вибери малюнок.':'Подивись і вибери правильну відповідь.',objective:'Recognize and use familiar English words',reviewStatus:'approved',likelyErrors:choices.filter(c=>c!==answer),...extra}}
const positionLesson:Lesson={level:'A1',id:'animals-1',topic:'animals',title:'Where is the little cat?',objective:'I can understand in, on, and under.',words:['cat','ball','box','in','on','under'],activities:[
activity('position-discover','discover','sentences','under','The cat is under the chair.','The cat is under the chair.','',[],'Under means below. Look below the seat.',{scene:{object:'cat',position:'under',surface:'chair'}}),
activity('position-listen','listen','listening','under','Listen. Which picture matches?','The cat is under the chair.','under',['on','under','in'],'Under means below the seat.',{scene:{object:'cat',position:'under',surface:'chair'}}),
activity('position-place','place','sentences','under','Put the ball under the table.','Put the ball under the table.','under',['in','on','under'],'Tap the ball, then tap below the table.',{scene:{object:'ball',position:'under',surface:'table'}}),
activity('position-build','build','sentences','under','Build a sentence about this picture.','The cat is under the chair.','The cat is under the chair.',['chair.','under','The','is','the','cat'],'Start with The cat. Where is it?',{scene:{object:'cat',position:'under',surface:'chair'}}),
activity('position-check','check','sentences','on','Where is the book?','Where is the book?','on',['under','in','on'],'On means resting on top.',{scene:{object:'book',position:'on',surface:'table'}}),
activity('position-in','check','sentences','in','Where is the ball?','Where is the ball?','in',['on','in','under'],'In means inside.',{scene:{object:'ball',position:'in',surface:'box'}})
]};
const groups=[['animals','At home','cat','dog','rabbit'],['animals','By the pond','bird','fish','duck'],['animals','On the farm','horse','cow','sheep'],['animals','Wild friends','frog','lion','elephant'],['food','Fruit for a picnic','apple','banana','orange'],['food','Breakfast time','bread','cheese','egg'],['food','Something to drink','milk','water','juice'],['food','In the garden','carrot','tomato','potato'],['food','Let’s have lunch','cake','rice','sandwich'],['school','Pack your bag','book','pencil','bag'],['school','Let’s draw','ruler','pen','crayon'],['school','In my classroom','chair','table','door'],['school','Look around','clock','window','computer'],['school','Ready to learn','ball','map','notebook']];
const counts:Record<string,number>={animals:1,food:0,school:0};
export const foundationLessons:Lesson[]=[positionLesson,...groups.map(([topic,title,...words])=>{const id=`${topic}-${++counts[topic]}`;const [a,b,c]=words;const sentence=`I can see ${['a','e','i','o','u'].includes(c[0])?'an':'a'} ${c}.`;return {level:'A1' as const,id,topic,title,objective:`I can recognize and use ${words.join(', ')}.`,words,activities:[activity(id+'-listen','listen','listening',a,'Listen and choose the picture.',a,a,words,`Look for ${glossary[a].picture}. This is ${a}.`,{pictures:true}),activity(id+'-read','match','reading',a,`Find the ${a}.`,a,a,[c,a,b],`The word ${a} matches ${glossary[a].picture}.`,{pictures:true}),activity(id+'-spell','spell','spelling',b,`Build the word for ${glossary[b].picture}.`,b,b,b.split('').reverse(),`The word starts with ${b[0]}.`,{pictures:true}),activity(id+'-build','build','sentences',c,`Make a sentence about ${glossary[c].picture}.`,sentence,sentence,sentence.split(' ').reverse(),'Start with I can see.')]}})];

export const levelCatalog:{id:Level;name:string;description:string;focus:string}[]=[
{id:'pre-A1',name:'First steps',description:'Meet familiar words with pictures, short phrases, and plenty of support.',focus:'Pictures, words, and short phrases'},
{id:'A1',name:'Everyday beginnings',description:'Recognize familiar language and build simple sentences about everyday life.',focus:'Familiar vocabulary and simple sentences'},
{id:'A2',name:'Everyday connections',description:'Understand everyday information and describe routines, experiences, and plans.',focus:'Descriptions, past events, and plans'},
{id:'B1',name:'Ideas & experiences',description:'Follow clear connected language and explain experiences and opinions with reasons.',focus:'Connected explanations and clear reasons'},
{id:'B2',name:'Perspectives & arguments',description:'Compare viewpoints, follow complex ideas, and support a detailed argument.',focus:'Inference, argument, and precise language'},
{id:'C1',name:'Meaning between the lines',description:'Interpret implied meaning, adapt your register, and organize a nuanced response.',focus:'Implicit stance, register, and synthesis'},
{id:'C2',name:'Precision & nuance',description:'Weigh subtle distinctions, reconcile perspectives, and reformulate ideas precisely.',focus:'Rhetorical nuance and precise reformulation'}
];
export function normalizeLevel(value:string):Level{return levelCatalog.some(l=>l.id===value)?value as Level:'pre-A1'}
export function levelInfo(value:string){return levelCatalog.find(l=>l.id===normalizeLevel(value))!}
export const lessons:Lesson[]=[...foundationLessons,...[...advancedContent,...grammarContent].map(l=>({...l,level:l.level as Level,activities:l.activities.map(a=>({...a,objective:l.objective,reviewStatus:'approved' as const,likelyErrors:a.choices.filter(c=>c!==a.answer)}))})) as Lesson[]];
export function lessonsForLevel(value:string){const level=normalizeLevel(value);return lessons.filter(l=>l.level===(level==='pre-A1'?'A1':level))}
export function levelForEvidence(e:Evidence):Level{return lessons.find(l=>l.id===e.lessonId)?.level??normalizeLevel(e.level??'A1')}
export function evidenceForLevel(evidence:Evidence[],value:string){const level=normalizeLevel(value);return evidence.filter(e=>levelForEvidence(e)===(level==='pre-A1'?'A1':level))}
export function validTargetWords(words:unknown):words is string[]{return Array.isArray(words)&&words.length>0&&words.length<=8&&words.every(w=>typeof w==='string'&&/^[a-z]+(?:[ '-][a-z]+)*$/i.test(w)&&w.length<=40)}
export function wordCount(text:string){return text.trim()?text.trim().split(/\s+/).length:0}
export function practiceCandidates(evidence:Evidence[],level:string,now=Date.now()){
 const latest=new Map<string,Evidence>();for(const e of evidence){const prev=latest.get(e.activityId);if(!prev||Date.parse(e.date)>=Date.parse(prev.date))latest.set(e.activityId,e)}
 return lessonsForLevel(level).flatMap(l=>l.activities.filter(a=>a.kind!=='discover'&&a.kind!=='write').map(a=>{
  const e=latest.get(a.id);const due=e?.status==='independent'&&now-Date.parse(e.date)>=7*86400000;
  const priority=e?.status==='insufficient'?12:e?.status==='supported'?9:due?8:!e?2:0;
  const reason=e?.status==='insufficient'?'Your last answer needs another try.':e?.status==='supported'?'You used support last time. Try recalling with less help.':due?'It has been at least a week since independent success.':!e?'A new example to check this skill.':'A fresh check of a recently practised skill.';
  return {id:a.id,lessonId:l.id,lessonTitle:l.title,skill:a.skill,item:a.item,objective:l.objective,priority,reason,lastStatus:e?.status??'not-tried',lastPractised:e?.date??null,attempts:evidence.filter(x=>x.activityId===a.id).length,assistance:e?.assistance??[]};
 })).sort((a,b)=>b.priority-a.priority).slice(0,18);
}

export const skillLabels:Record<Skill,string>={listening:'Listening comprehension',reading:'Reading comprehension',sentences:'Understanding & building sentences',spelling:'Spelling words',speaking:'Speaking',writing:'Writing and expression'};
export type Evidence={id:string;activityId:string;lessonId:string;skill:Skill;item:string;firstResponse:string;response:string;correct:boolean;assistance:string[];status:'independent'|'supported'|'insufficient'|'pending-review';level?:Level;review?:{feedback:string;criteria:boolean[];date:string};date:string};
export const defaults={nickname:'little explorer',ageBand:'7–9',reading:'early reader',level:'beginner',uk:false,large:false,spacing:false,reduced:false,rate:0.85,microphone:false,assignment:''};
export type Profile=typeof defaults;
export function assess(first:string,response:string,answer:string,assistance:string[]){const correct=response===answer;return {correct,status:(!correct?'insufficient':first===answer&&!assistance.length?'independent':'supported') as Evidence['status']}}
export function assessGap(first:string,response:string,a:Activity,assistance:string[]){const norm=(s:string)=>s.trim().toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g,' ').replace(/[.!?]+$/,'');const answers=(a.answers??[a.answer]).map(norm);const correct=answers.includes(norm(response));return {correct,status:(!correct?'insufficient':answers.includes(norm(first))&&!assistance.length?'independent':'supported') as Evidence['status']}}
export function recommend(evidence:Evidence[],profile:Profile,now=Date.now()){
 const bank=lessonsForLevel(profile.level);const ids=new Set(bank.map(l=>l.id));
 evidence=evidence.filter(e=>ids.has(e.lessonId));
 const assigned=bank.find(l=>l.id===profile.assignment);if(assigned)return {lesson:assigned,reason:'Your teacher chose this lesson for your current learning path.',rule:'teacher-override'};
 const latest=new Map<string,Evidence>();for(const e of evidence){const old=latest.get(e.activityId);if(!old||Date.parse(e.date)>=Date.parse(old.date))latest.set(e.activityId,e)}
 const records=[...latest.values()].sort((a,b)=>Date.parse(a.date)-Date.parse(b.date));
 const overdue=records.find(e=>e.status==='independent'&&now-Date.parse(e.date)>7*86400000);if(overdue)return {lesson:bank.find(l=>l.id===overdue.lessonId)!,reason:'A short review will help you remember what you learned at this level.',rule:'delayed-recall'};
 const recent=records.slice(-12);const confusion=recent.filter(e=>e.status==='insufficient');if(confusion.length>=2)return {lesson:bank.find(l=>l.id===confusion.at(-1)?.lessonId)!,reason:'Explore a clearer example, then try a fresh response.',rule:'contrast-and-recheck'};
 const support=recent.filter(e=>e.status==='supported');if(support.length>=2)return {lesson:bank.find(l=>l.id===support.at(-1)?.lessonId)!,reason:'You found answers with help. Try again with a little less support.',rule:'fade-support'};
 const listening=new Set(records.filter(e=>e.skill==='listening'&&e.status==='independent').map(e=>e.item));const gap=records.find(e=>e.skill==='reading'&&e.status!=='independent'&&listening.has(e.item));if(gap)return {lesson:bank.find(l=>l.id===gap.lessonId)!,reason:'You understood this by listening. Now explore it in writing.',rule:'reading-bridge'};
 const next=bank.find(l=>l.activities.filter(a=>a.kind!=='discover').some(a=>!['independent','pending-review'].includes(latest.get(a.id)?.status??'')));
 if(next)return {lesson:next,reason:'Build the next skill within your selected learning path.',rule:'next-independent-skill'};
 const pending=records.find(e=>e.status==='pending-review');if(pending)return {lesson:bank.find(l=>l.id===pending.lessonId)!,reason:'Your writing is waiting for teacher feedback. You can revisit this lesson meanwhile.',rule:'awaiting-teacher-review'};
 return {lesson:bank[0],reason:'You have practised this sample path. Revisit it or ask an adult to choose another level; completion is not a CEFR qualification.',rule:'level-review'};
}
export const stories=[{id:'cat',title:'Milo and the missing ball',topic:'animals',emoji:'🐈',lines:['Milo is a cat.','Milo has a ball.','The ball is under the chair.','A dog can see the ball.','Milo and the dog play.'],question:'Where is the ball?',answer:'Under the chair',choices:['In the bag','Under the chair','On the table']},{id:'picnic',title:'A picnic for two',topic:'food',emoji:'🧺',lines:['I have a bag.','An apple is in the bag.','I have bread and cheese.','My friend has a banana.','We like our picnic.'],question:'What does the friend have?',answer:'A banana',choices:['A banana','An egg','A carrot']},{id:'school',title:'Pip goes to school',topic:'school',emoji:'🎒',lines:['Pip has a bag.','A book is in the bag.','A pencil is on the table.','Pip can see a map.','It is time to learn.'],question:'Where is the pencil?',answer:'On the table',choices:['In the bag','Under the chair','On the table']}];
